services:

  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=silen.locatelli@gmx.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  me:
    image: "ghcr.io/lunchtimecode/me:${me_VERSION}"
    container_name: "me"
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.me.rule=Host(`me.silenlocatelli.ch`)"
      - "traefik.http.routers.me.entrypoints=websecure"
      - "traefik.http.routers.me.tls.certresolver=myresolver"
    
  akita:
    container_name: akita
    image: akitasoftware/cli:latest
    depends_on:
        - me
    environment:
      - AKITA_API_KEY_ID=${AKITA_API_KEY_ID}
      - AKITA_API_KEY_SECRET=${KITA_API_KEY_SECRET}
    network_mode: "service:me"
    entrypoint: /akita apidump --service me   