services:
  traefik:
    dns:
          - 8.8.8.8
          - 1.1.1.1
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=silen.locatelli@gmx.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  me:
    image: "ghcr.io/lunchtimecode/me:${me_VERSION}"
    container_name: "me"
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.me.rule=Host(`me.silenlocatelli.ch`)"
      - "traefik.http.routers.me.entrypoints=websecure"
      - "traefik.http.routers.me.tls.certresolver=myresolver"
      
  jobs:
    image: "ghcr.io/lunchtimecode/jobs:${jobs_VERSION}"
    container_name: "jobs"
    ports:
      - "8001:12500"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobs.rule=Host(`jobs.silenlocatelli.ch`)"
      - "traefik.http.routers.jobs.entrypoints=websecure"
      - "traefik.http.routers.jobs.tls.certresolver=myresolver"